FROM node:20-alpine AS builder
WORKDIR /app
COPY backend/package*.json backend/tsconfig.json ./
RUN npm ci
COPY backend ./
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist
EXPOSE 5000
CMD ["node","dist/server.js"]
